console.log('hello c-build')

import './styles/index.css'
import defaultFn, { sayHello } from './utils/index.js'
function init () {
    const app = document.createElement('div')
    app.id = 'app'
    app.style = `
    height: 100vh;
    width: 100vw;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    `
    const h1 = document.createElement('h1')
    h1.innerHTML = `
    <span style="color: coral">
        hello c-build, this str is generated by js
        <span style="color: slateblue">modify this str and see the result</span>
    </span>
    `

    app.appendChild(h1)
    document.body.appendChild(app)
}

console.log('modify this str and see the result')

init()

defaultFn()
sayHello()